answer_words = ["جی بھائی؟ کوئی مسئلہ؟", "بس یار فوجی زندگی!", "کیا اس سے آپ کو کوئی فرق پڑتا ہے ؟؟؟", "گزارا ہے بس!",
                "فٹ فاٹ, آپ سنائیں!",
                "زندگی میں چلنا ہے تو اچھی طرح چل, ورنہ ایسا سبق سکھاؤں گا کہ چار دن کی زندگی دو دن کی رہ جائے گی!",
                "میں غریب ہوں!", "روک سکو تو روک لو, میں تمہیں رلاؤں گا!", "میں ترے خوابوں میں آؤں گا!",
                "الله کی قسم,  میں ترے خوابوں میں آؤں گا!", "ہاہاہا, ٹھیک ہوں!"]

question_words = ["G. Kaisy ho G?", "G. How are you?", "G. Kaisa h?", "G. Kaisy h jani?", "G. Zindgi kaisy guzr rhi?",
                  "G. Kesa h ?", "G.sb set h?", "G.kuxh sunao"]

playlist = ["https://youtube.com/watch?v=QG9Nq1IHTKo&feature=share",
            "https://youtube.com/watch?v=XpEMGGbTH9o&feature=share",
            "https://youtube.com/watch?v=XpEMGGbTH9o&feature=share",
            "https://youtube.com/watch?v=cAIfMjmAGfc&feature=share",
            "https://youtube.com/watch?v=INlu5lQEdW8&feature=share",
            "https://youtube.com/watch?v=lX2ZhNND_lQ&feature=share",
            "https://youtube.com/watch?v=HbT422WobZ8&feature=share",
            "https://youtube.com/watch?v=aQSUmfj8XbM&feature=share",
            "https://youtube.com/watch?v=Z3pdUsehWfE&feature=share",
            "https://youtube.com/watch?v=mowLIWwo5HA&feature=share",
            "https://youtube.com/watch?v=ketyd3RISPU&feature=share",
            "https://youtube.com/watch?v=B__eixl8-Cs&feature=share"
            ]

list = ["contessa",
        "avatar",
        "mini",
        "bigfig",
        "lcd",
        "bubble",
        "digital",
        "twopoint",
        "3x5",
        "threepoint",
        "ascii_new_roman",
        "bulbhead",
        "lockergnome", "contessa",
        "xhelvi",
        "utopiai",
        "rev",
        "smpoison",
        "3-d",
        "larry3d",
        "nancyj",
        "nancyj-underlined",
        "os2",
        "block2", "soft",
        "4max",
        "5x7",
        "stampate",
        "o8",
        "standard",
        "alphabet",
        "computer",
        "shadow",
        "speed",
        "rounded",
        "chartri",
        "1943",
        "4x4_offr",
        "64f1",
        "a_zooloo",
        "advenger",
        "aquaplan",
        "assalt_m",
        "asslt_m",
        "atc",
        "atc_gran",
        "battlesh",
        "baz_bil",
        "beer_pub",
        "c1",
        "c2",
        "c_consen",
        "char1",
        "char4",
        "coil_cop",
        "druid",
        "faces_of",
        "fair_mea",
        "fairligh",
        "fantasy",
        "fbr1",
        "fbr12",
        "fbr_stri",
        "fbr_tilt",
        "finalass",
        "fp1",
        "fp2",
        "funky_dr",
        "future_1",
        "future_2",
        "future_3",
        "future_4",
        "future_5",
        "future_6",
        "future_7",
        "future_8",
        "ghost_bo",
        "grand_pr",
        "green_be",
        "hades",
        "heavy_me",
        "heroboti",
        "house_of",
        "hypa_bal",
        "hyper",
        "kgames_i",
        "kik_star",
        "krak_out",
        "tsn_base",
        "ugalympi",
        "unarmed",
        "usa",
        "usa_pq",
        "vortron",
        "war_of_w",
        "yie-ar",
        "yie_ar_k",
        "z-pilot",
        "zig_zag",
        "zone7",
        "dotmatrix",
        "univers",
        "doh",
        "roman",
        "hollywood",
        "georgia11",
        "block"
        ]

SMALL_WIZARD_FONT = [
    "contessa",
    "avatar",
    "mini",
    "bigfig",
    "lcd",
    "bubble",
    "digital",
    "twopoint",
    "3x5",
    "threepoint",
    "ascii_new_roman",
    "bulbhead",
    "lockergnome"]  # pragma: no cover
MEDIUM_WIZARD_FONT = [
    "soft",
    "4max",
    "5x7",
    "stampate",
    "o8",
    "standard",
    "alphabet",
    "computer",
    "shadow",
    "speed",
    "rounded",
    "chartri"]  # pragma: no cover
LARGE_WIZARD_FONT = [
    "xhelvi",
    "utopiai",
    "rev",
    "smpoison",
    "3-d",
    "larry3d",
    "nancyj",
    "nancyj-underlined",
    "os2",
    "block2"]  # pragma: no cover
XLARGE_WIZARD_FONT = [
    "dotmatrix",
    "univers",
    "doh",
    "roman",
    "hollywood",
    "georgia11",
    "block"]  # pragma: no cover

UPPERCASE_FONTS = [
    "1943",
    "4x4_offr",
    "64f1",
    "a_zooloo",
    "advenger",
    "aquaplan",
    "assalt_m",
    "asslt_m",
    "atc",
    "atc_gran",
    "battlesh",
    "baz_bil",
    "beer_pub",
    "c1",
    "c2",
    "c_consen",
    "char1",
    "char4",
    "coil_cop",
    "druid",
    "faces_of",
    "fair_mea",
    "fairligh",
    "fantasy",
    "fbr1",
    "fbr12",
    "fbr_stri",
    "fbr_tilt",
    "finalass",
    "fp1",
    "fp2",
    "funky_dr",
    "future_1",
    "future_2",
    "future_3",
    "future_4",
    "future_5",
    "future_6",
    "future_7",
    "future_8",
    "ghost_bo",
    "grand_pr",
    "green_be",
    "hades",
    "heavy_me",
    "heroboti",
    "house_of",
    "hypa_bal",
    "hyper",
    "kgames_i",
    "kik_star",
    "krak_out",
    "tsn_base",
    "ugalympi",
    "unarmed",
    "usa",
    "usa_pq",
    "vortron",
    "war_of_w",
    "yie-ar",
    "yie_ar_k",
    "z-pilot",
    "zig_zag",
    "zone7"]

NON_ASCII_ARTS = [
    '3',
    '5',
    '9/11 truth',
    'acid',
    'afraid',
    'airplane1',
    'airplane2',
    'airplane3',
    'ak-47',
    'almost cared',
    'american money2',
    'american money3',
    'american money4',
    'american money5',
    'angry birds',
    'angry face',
    'angry face2',
    'angry troll',
    'angry',
    'angry2',
    'ankush',
    'arrow1',
    'arrowhead',
    'at what cost',
    'awkward',
    'band aid',
    'barbell',
    'barcode1',
    'barcode2',
    'barf',
    'basking in glory',
    'bautista',
    'bear GTFO',
    'bear squiting',
    'bear',
    'bear2',
    'because',
    'bee',
    'being draged',
    'bender',
    'big eyes',
    'big nose',
    'bird',
    'birds',
    'bomb',
    'boombox1',
    'boombox2',
    'boxing',
    'breakdown',
    'british money',
    'bullshit',
    'butt',
    'butterfly',
    'camera',
    'car race',
    'careless',
    'cassette1',
    'cassette2',
    'cat face',
    'cat smile',
    'cat2',
    'cat4',
    'catlenny',
    'chair',
    'chasing',
    'cheer',
    'cheers',
    'chess pieces',
    'chess',
    'chicken',
    'chu',
    'cigarette1',
    'club bold',
    'club regular',
    'coffee now',
    'confused scratch',
    'confused3',
    'confused5',
    'confused6',
    'confused7',
    'confused8',
    'confused9',
    'crayons',
    'crazy',
    'creeper',
    'cry face',
    'cry troll',
    'cry',
    'crying1',
    'cup1',
    'cup2',
    'cute cat',
    'cute face',
    'cute face2',
    'cute face3',
    'cute face4',
    'cute face5',
    'cute face6',
    'cute face7',
    'cute face8',
    'cute face9',
    'upset',
    'dab',
    'dalek',
    'damnyou',
    'dance2',
    'dancee',
    'dancing people',
    'dancing',
    'dead eyes',
    'dear god why',
    'decorate',
    'depressed',
    'derp',
    'devious smile',
    'dgaf',
    'diamond bold',
    'diamond regular',
    'disagree',
    'discombobulated',
    'dislike1',
    'dislike2',
    'do you even lift bro?',
    'double flip',
    'drowning',
    'drunkenness',
    'dunno',
    'dunno2',
    'dunno3',
    'dunno4',
    'dunno5',
    'electrocardiogram1',
    'electrocardiogram2',
    'electrocardiogram3',
    'electrocardiogram4',
    'elephant',
    'emo dance',
    'energy',
    'envelope',
    'epic gun',
    'equalizer',
    'error',
    'exchange',
    'excited',
    'exorcism',
    'eye closed',
    'eye roll',
    'eyes',
    'face',
    'facepalm',
    'fail',
    'fart',
    'feel perky',
    'fido',
    'fight',
    'finger1',
    'finger2',
    'finger3',
    'finger4',
    'finn',
    'fish invasion',
    'fish swim',
    'fish3',
    'fisticuffs',
    'flex',
    'flip friend',
    'fly away',
    'flying',
    'formula1 car',
    'french kiss',
    'frown',
    'fu',
    'fuck you2',
    'fuckall',
    'fungry',
    'ghost',
    'gimme',
    'glasses2',
    'glitter',
    'go away bear',
    'gotit',
    'gtalk fit',
    'guitar',
    'gun1',
    'gun2',
    'gun3',
    'gun4',
    'hairstyle',
    'happy birthday 1',
    'happy face',
    'happy hug',
    'happy square',
    'happy',
    'happy2',
    'happy3',
    'happy6',
    'happy7',
    'happy8',
    'happy9',
    'happy10',
    'happy11',
    'happy12',
    'happy13',
    'happy14',
    'happy15',
    'happy16',
    'happy17',
    'happy18',
    'happy19',
    'happy20',
    'happy21',
    'happy22',
    'happy23',
    'happy24',
    'happy25',
    'happy26',
    'happy27',
    'head shot',
    'heart bold',
    'heart regular',
    'heart1',
    'heart2',
    'hell yeah',
    'hello',
    'hello2',
    'help',
    'high five',
    'hitchhicking',
    'honeycute',
    'house',
    'hug me',
    'hugger',
    'huhu',
    'hybrix',
    'i dont care',
    'i kill you',
    'im a hugger',
    'injured',
    'inlove',
    'innocent face',
    'japanese lion face',
    'jaymz',
    'jazz musician',
    'john lennon',
    'joker1',
    'joker2',
    'joker3',
    'joker4',
    'jokeranonimous',
    'jokeranonimous2',
    'judgemental',
    'judging',
    'kablewee',
    'killer',
    'kilroy was here',
    'kirby',
    'kissing',
    'kissing2',
    'kissing3',
    'kissing4',
    'kissing5',
    'kissing6',
    'kiss2',
    'kiss3',
    'kitty emote',
    'kokain',
    'kyubey',
    'kyubey2',
    'laughing',
    'lenny',
    'line brack',
    'listening to headphones',
    'loading1',
    'loading2',
    'loading3',
    'loading4',
    'loading5',
    'loading6',
    'looking face',
    'love in my eye1',
    'love in my eye2',
    'love in my eye3',
    'love',
    'love2',
    'love3',
    'love4',
    'man spider',
    'spider4',
    'man tears',
    'mango',
    'med man',
    'med',
    'meditation',
    'meep',
    'meow',
    'monocle',
    'monster',
    'monster2',
    'mouse2',
    'mouse3',
    'mouse4',
    'myancat',
    'nathan',
    'needle1',
    'neo',
    'no support',
    'nose',
    'opera',
    'owlkin',
    'pac man',
    'panda',
    'party time',
    'peace yo!',
    'peepers',
    'penis2',
    'perky',
    'pig2',
    'piggy',
    'ping pong',
    'pirate',
    'pistols1',
    'pistols2',
    'pistols3',
    'pistols4',
    'pistols5',
    'mad',
    'mad2',
    'mad5',
    'mad6',
    'mad7',
    'mad9',
    'mad10',
    'playing cards clubs',
    'playing cards clubs waterfall',
    'playing cards diamonds',
    'playing cards diamonds waterfall',
    'playing cards hearts',
    'playing cards hearts waterfall',
    'playing cards spades',
    'playing cards spades waterfall',
    'playing cards',
    'playing cards waterfall',
    'playing cards waterfall (trump)',
    'playing in snow',
    'point',
    'polar bear',
    'pretty eyes',
    'professor',
    'puls',
    'put the table back',
    'rak',
    'rare',
    'real face',
    'religious',
    'resting my eyes',
    'robber',
    'robot boy',
    'robot2',
    'robot3',
    'rocket',
    'rope',
    'round bird',
    'running',
    'sad and confused',
    'sad and crying',
    'sad face',
    'sad1',
    'sad2',
    'sad3',
    'sad4',
    'sad5',
    'sat',
    'satan',
    'satisfied',
    'scissors',
    'seal',
    'sex symbol',
    'shark face',
    'sheep',
    'shocked1',
    'shrug',
    'shy',
    'singing',
    'singing2',
    'sky free',
    'sleepy coffee',
    'sleepy',
    'slenderman',
    'smooth',
    'smug bastard',
    'sniper rifle',
    'sniperstars',
    'snowing',
    'snowman1',
    'sorreh bro',
    'spade bold',
    'spade regular',
    'sparkling heart',
    'spell cast',
    'squee',
    'squid',
    'srs face',
    'staring',
    'stars',
    'stars2',
    'stranger danger',
    'strut',
    'stunna shades',
    'sunglasses1',
    'sunny day',
    'surprised2',
    "surprised4",
    "surprised5",
    "surprised6",
    "surprised8",
    "surprised9",
    "surprised10",
    "surprised11",
    "surprised12",
    "surprised13",
    "surprised15",
    "surprised16",
    "surprised17",
    "surprised18",
    "surprised19",
    "surprised20",
    'sword2',
    'sword3',
    'sword8',
    'sword9',
    'table flip',
    'table flip2',
    'table flip3',
    'table flip4',
    'table flip5',
    'table flip6',
    'table flip7',
    'table flip8',
    'table flip9',
    'table flip10',
    'taking a dump',
    'teddy',
    'telephone',
    'tgif',
    'things that can_t be unseen',
    'tidy up',
    'tie-fighter',
    'tired',
    'touchy feely',
    'toungue out1',
    'train',
    'tripping out',
    'trolling',
    'umadbro',
    'up',
    'upsidedown',
    'wat',
    'wat-wat',
    'waves',
    'weather',
    'what?',
    'what??',
    'whisling',
    'why',
    'winnie the pooh',
    'winning',
    'wizard',
    'wizard2',
    'woman',
    'worried',
    'wtf dude?',
    'yessir',
    'yolo',
    'yun',
    'zable',
    'zoidberg',
    'zombie',
    'zombie2',
    'zoned',
    'swim',
    'swim2',
    'swim3',
    'yawning',
    'boobs2']
